name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      env:
        DEVELOPER_DIR: /Applications/Xcode_15.0.1.app
      run: xcodebuild test -scheme Xcodes
